title: Vikas KM
description: Personal Tech Blog

url: vikas-km.github.io
baseurl:
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: vikas-km
  email: vikki.km@gmail.com
  linkedin: vikaskm

google_analytics: 
disqus:
    shortname: vikaskm
